In [1]:
import pandas as pd
df= pd.read_csv('data/dataset.csv')
df.shape

(114000, 21)

In [2]:
df=dropna()
df=df.drop(columns=['Unnamed: 0'])
df.shape

NameError: name 'dropna' is not defined

In [5]:
df=df.dropna()
df=df.drop(columns=['Unnamed;0'])
df.shape

KeyError: "['Unnamed;0'] not found in axis"

In [4]:
df.shape

(113999, 21)

In [6]:
df.shape

(113999, 21)

In [7]:
df=df.dropna()

In [8]:
df=df.drop(columns=['Unnamed: 0'])

In [9]:
df.shape

(113999, 20)

In [10]:
df.drop_duplicates(subset=['track_name', 'artists'])

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,5,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,0,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,0,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,7,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,1,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

In [11]:
df=df.reset_index(drop=True)
df.head()

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [12]:
df.shape

(113999, 20)

In [13]:
df = df.drop_duplicates(subset=['track_name', 'artists'])
df.shape

(81343, 20)

In [14]:
df=df.reset_index(drop=True)
df.head()

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [15]:
df.shape

(81343, 20)

In [16]:
df.to_csv('data/clean_tracks.csv', index=False)

In [17]:
import os
os.listdir('data')

['clean_tracks.csv', 'dataset.csv']

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
feature_cols =['danceability', 'energy', 'valence', 'tempo', 'acousticness', 'loudness', 'speechiness']
X = df[feature_cols]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [20]:
X_scaled.shape

(81343, 7)

In [21]:
from sklearn.neighbors import NearestNeighbors

model= NearestNeighbors(n_neighbors=11, metric='cosine')
model.fit(X_scaled)

NearestNeighbors(metric='cosine', n_neighbors=11)

In [22]:
df recommend(song_name, n=10):
   matches = df[df['track_name'].str.lower() == song_name.lower()]
   if matches.empty:

SyntaxError: invalid syntax (3764539749.py, line 1)

In [23]:
def recommend(song_name, n=10):
    matches = df[df['track_name'].str.lower() == song_name.lower()]
    
    if matches.empty:
        return "Song not found. Try another one."
    
    idx = matches.index[0]
    distances, indices = model.kneighbors([X_scaled[idx]], n_neighbors=n+1)
    
    similar_indices = indices[0][1:]
    return df.iloc[similar_indices][['track_name', 'artists']]

In [24]:
recommend("Blinding Lights")

                   track_name               artists
48830                 One Day            Omoinotake
47988                  PLAYER             PASSEPIED
1295               Pinga Fogo      Nomade Orquestra
403    You Are the Best Thing        Ray LaMontagne
31143                Mob Rule           Bad//Dreems
79654                Benmişim                   Nev
27135                 Atrakce  PAWLIE POIZN;Medooza
48560                    言って。                  ヨルシカ
71928                  Me Voy         Los Victorios
16868               My Person      Spencer Crandall

In [25]:
recommend("Perfect")

,track_name,artists
44046,Kya Tum Naraaz Ho? (Raw),Tanmaya Bhatnagar
52434,Aaradhike - Ambili - Malayalam Song,Noel Toms
36339,When Pueo Flies,Charles Michael Brotman;Robi Kahakalau
66622,"Когда весна придёт - Из к/ф ""Весна на Заречной...",Николай Рыбников
59802,The Call,Regina Spektor
65822,Ésta Es Mi Historia,Los Solitarios
57204,September Moon,Tony O'Connor
28022,Heartbeats,José González
9577,The Eternal Recurrence,Gerald Barry;Jennifer France;Britten Sinfonia;...
36836,Ao Clarear,Dieter Huber

In [26]:
import joblib

joblib.dump(model, 'models/nn_model.pk1')
joblib.dump(scaler, 'models/scaler.pk1')

['models/scaler.pk1']

In [27]:
import os

In [28]:
os.listdir('models')

['nn_model.pk1', 'scaler.pk1']

In [1]:
import sys
sys.path.append('.')
from src.queries import top_genres_by_popularity

top_genres_by_popularity()

ModuleNotFoundError: No module named 'src.queries'

In [2]:
import os
os.listdir('src')

['src']

In [3]:
import os
os.getcwd()

'/Users/aryaaditya/Desktop/music-recommender'

In [4]:
os.listdir('src/src')

['queries.py']

In [1]:
import sys
sys.path.append('.')
from src.queries import top_genres_by_popularity

top_genres_by_popularity()

          track_genre  avg_popularity  num_tracks
0               k-pop           59.33         854
1            pop-film           59.12         808
2               metal           56.45         213
3                 pop           55.91         299
4               chill           55.15         910
5             hip-hop           52.53         659
6                 sad           51.81         536
7              latino           51.17         332
8              grunge           50.56         744
9   singer-songwriter           49.83         432
10             indian           49.79         722
11                emo           49.54         866
12              piano           49.03         688
13                edm           48.73         510
14              anime           48.64         942