In [1]:
import pandas as pd
import sqlite3

df=pd.read_csv('data/clean_tracks.csv')
df.shape

(81343, 20)

In [2]:
conn = sqlite3.connect('data/music.db')
df.to_sql('tracks', conn, if_exists='replace', index=False)

81343

In [3]:
query ="SELECT track_name, artists, popularity FROM tracks ORDER BY popularity DESC LIMIT 10"
pd.read_sql(query, conn)

,track_name,artists,popularity
0,Unholy (feat. Kim Petras),Sam Smith;Kim Petras,100
1,"Quevedo: Bzrp Music Sessions, Vol. 52",Bizarrap;Quevedo,99
2,I'm Good (Blue),David Guetta;Bebe Rexha,98
3,La Bachata,Manuel Turizo,98
4,Me Porto Bonito,Bad Bunny;Chencho Corleone,97
5,Tití Me Preguntó,Bad Bunny,97
6,Under The Influence,Chris Brown,96
7,Efecto,Bad Bunny,96
8,I Ain't Worried,OneRepublic,96
9,Ojitos Lindos,Bad Bunny;Bomba Estéreo,95

In [4]:
query = ""
SELECT track_genre, ROUND(AVG(popularity), AS avg_popularity, COUNT(*) AS num_tracks
FROM tracks
GROUP BY track_genre
ORDER BY avg_popularity DESC

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3932921712.py, line 2)

In [5]:
query = """
SELECT track_genre, ROUND(AVG(popularity), 2) AS avg_popularity, COUNT(*) AS num_tracks
FROM tracks
GROUP BY track_genre
ORDER BY avg_popularity DESC
LIMIT 15
"""
pd.read_sql(query, conn)

          track_genre  avg_popularity  num_tracks
0               k-pop           59.33         854
1            pop-film           59.12         808
2               metal           56.45         213
3                 pop           55.91         299
4               chill           55.15         910
5             hip-hop           52.53         659
6                 sad           51.81         536
7              latino           51.17         332
8              grunge           50.56         744
9   singer-songwriter           49.83         432
10             indian           49.79         722
11                emo           49.54         866
12              piano           49.03         688
13                edm           48.73         510
14              anime           48.64         942

In [6]:
query = """
SELECT 
  CASE 
    WHEN danceability < 0.33 THEN 'Low danceability'
    WHEN danceability < 0.66 THEN 'Medium danceability'
    ELSE 'High danceability'
  END AS danceability_group,
  ROUND(AVG(popularity), 2) AS avg_popularity,
  COUNT(*) AS num_tracks
FROM tracks
GROUP BY danceability_group
ORDER BY avg_popularity DESC
"""
pd.read_sql(query, conn)

    danceability_group  avg_popularity  num_tracks
0    High danceability           35.47       25465
1  Medium danceability           35.34       46597
2     Low danceability           28.83        9281

In [7]:
query = """
SELECT explicit, ROUND(AVG(popularity), 2) AS avg_popularity, COUNT(*) AS num_tracks
FROM tracks
GROUP BY explicit
"""
pd.read_sql(query, conn)

   explicit  avg_popularity  num_tracks
0         0           34.26       74385
1         1           38.69        6958

In [8]:
correlations = df[['popularity', 'danceability', 'energy', 'valence', 'tempo', 'acousticness', 'loudness', 'speechiness']].corr()['popularity'].sort_values(ascending=False)
correlations

popularity      1.000000
loudness        0.090162
danceability    0.087245
valence         0.011323
tempo           0.001891
energy         -0.000871
acousticness   -0.032143
speechiness    -0.064913
Name: popularity, dtype: float64

In [9]:
import sys
sys.path.append('.')
from src.queries import top_genres_by_popularity

top_genres_by_popularity()

ModuleNotFoundError: No module named 'src.queries'